### ISSUE TITLE
Could you tell me which version of botorch and scipy you are using?

### ISSUE THREAD

**Issue by jhrsya** [aoiang/LaMOO#1]
I am using botorch 0.7.2 and I got some bugs with botorch. Such as `from botorch.utils.multi_objective.box_decomposition import NondominatedPartitioning` in molecule/MCTS.py 37 lines. 

I got this bug when I run LaMOO/branincurrin/MCTS.py.
![image](https://user-images.githubusercontent.com/54741554/200243492-d46cafd0-25a5-4076-9997-a05502e099b6.png)
It seems there are some wrongs with scipy package. (I am using scipy 1.8.1). Thankyou very much!

**Comment by aoiang** [comment]
I was using version 0.3.4.dev15+g81df5c74. Feel free to try it. Thanks for asking.
